import { Component } from '@angular/core';
import { SimpleGridComponent,ExecutiveGridComponent } from '../../projects/frontek/src/public-api';

@Component({
  selector: 'app-root',
  imports: [SimpleGridComponent,ExecutiveGridComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'frontek-angular';

  headers = [
    { field: 'mlb', header: 'MLB' },
    { field: 'fornecedor', header: 'Fornecedor' },
    { field: 'envio', header: 'Envio' },
    { field: 'status', header: 'Status' },
    { field: 'preco_ativo', header: 'Preço Ativo' },
    { field: 'margem_ativa', header: 'Margem Ativa' },
    { field: 'preco_ganhar_catalogo', header: 'Preço Ganhar Catálogo' },
    { field: 'margem_ganhar_catalogo', header: 'Margem Ganhar Catálogo' },
    { field: 'margem_minima', header: 'Margem Mínima' },
    { field: 'margem_objetivo', header: 'Margem Objetivo' },
    { field: 'comissao', header: 'Comissão' },
    { field: 'imposto', header: 'Imposto' },
    { field: 'taxa_fixa', header: 'Taxa Fixa' },
    { field: 'frete', header: 'Frete' },
    { field: 'custo_sku', header: 'Custo Sku' },
  ];

  subheaders = [
    { field: 'nome', header: 'Nome' },
    { field: 'tipo', header: 'Tipo' },
    { field: 'ativo', header: 'Ativo' },
    { field: 'margem', header: 'Margem' },
    { field: 'rebate', header: 'Rebate' },
    { field: 'data_inicio', header: 'Data Inicio' },
    { field: 'data_termino', header: 'Data Término' },
    { field: 'campanha_valida', header: 'Campanha Válida' },
    { field: 'comissao_vendedor', header: 'Comissão Vendedor' },
  ];

  filter = {
    fieldToFilter: 'status',
    filters: [
      { label: 'Todos', value: '' },
      { label: 'Ativo', value: 'active' },
      { label: 'On Leave', value: 'on leave' },
    ]
  };

  data = [
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_796127-MLU70370396427_072023-O.jpg`,tags:[{text:'LI020-FRPRF'}],link:'https://http2.mlstatic.com/D_796127-MLU70370396427_072023-O.jpg'},
      fornecedor: {text:'KAPPESBERG'},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_764612-MLA42476973521_072020-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstafdafaftic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
    {
      mlb: {text:'MLB4563170846',image:`https://http2.mlstatic.com/D_956915-MLU77118725640_062024-O.jpg`,tags:[{text:'LI020-FRPRF'}]},
      fornecedor: {text:'KAPPESBERG'},
      link: {text:''},
      envio: {text:'me2'},
      status: {text:'perdendo', type:'badge', color: 'red'},
      preco_ativo: {text:'R$ 335,15'},
      margem_ativa: {text:'R$ 78,64'},
      preco_ganhar_catalogo: {text:'R$ 395,00'},
      margem_ganhar_catalogo: {text:'0,07%'},
      margem_minima: {text:'5,00%'},
      margem_objetivo: {text:'10,00%'},
      comissao: {text:'R$ 72,91'},
      imposto: {text:'R$ 64,35'},
      taxa_fixa: {text:'R$ 0,00'},
      frete: {text:'R$ 98,95'},
      custo_sku: {text:'R$ 139,19'},
      subdatas: {
        nome: {text:'saia na frente da concorrência'},
        tipo: {text:'PRICE_MATCHING'},
        ativo: {text:'Não', type:'badge', color: 'red'},
        margem: {text:'3.67%'},
        rebate: {text:'4,60%'},
        data_inicio: { text: '10/06/2025' },
        data_termino: { text: '19/06/2025' },
        campanha_valida: { text: 'Não', type: 'badge', color: 'red' },
        comissao_vendedor: { text: 'R$ 0,00' }
      }
    },
  ]

  // data = [
  //   {
  //     fullName: {
  //       text: 'Alice',
  //       image: `https://http2.mlstatic.com/D_NQ_NP_783991-MLB84824567917_052025-O-cadeira-kappesberg-sala-de-jantar-cozinha-metal-marrom-2-un.webp`,
  //       description: 'De Abreu'
  //     },
  //     department: {
  //       text: 'Marketing',
  //       tags:[
  //         { text: 'Digital Marketing' },
  //         { text: 'Content Creation' },
  //         { text: 'SEO' }
  //       ]
  //     },
  //     position: { text: 'Marketing Strategist'},
  //     email: { text: 'Alice@gmail.com'},
  //     phone: { text: '555-1234'},
  //     office: { text: 'New York Office'},
  //     hireDate: { text: '2020-05-15'},
  //     employeeId: { text: 'EMP001'},
  //     status: { text:'Active',type:'badge', color: 'green' },
  //     subdatas: {
  //       projectName: 'Product Launch Q3',
  //       role: 'Lead Strategist',
  //       status: 'In Progress'
  //     }
  //   },
  // ];

  headerBackgroundColor = 'lightgray';
  bodyBackgroundColor = 'red';
  textColor = 'black';
  textFontSize = '16px';
  textAlign = 'left';

}
